create table categoria (id int4 generated by default as identity, descricao varchar(200), nome varchar(100), primary key (id));
create table livro (id int4 generated by default as identity, nome_autor varchar(50), texto varchar(2000000), titulo varchar(50), categoria_id int4, primary key (id));
alter table if exists livro add constraint FK823wf30ms4bomdmqk9xekpv6c foreign key (categoria_id) references categoria;
